# These are supported funding model platforms

github: FlechazoPh
patreon: flechazo
open_collective: qldependency # Replace with a single Open Collective username
ko_fi: flechazo # Replace with a single Ko-fi username
custom: https://github.com/FlechazoPh/QLDependency/blob/56396ba27ef724da859dc1517787f502db5be7c8/assets/4B6DD0C1-8ECE-4C09-A0F7-3B6A36F399E7.jpeg
